// Local prototype only. The shared logical counter simulates operation ordering;
// real devices will need independent clocks, authenticated operations and durable logs.
const meetings = [
 {id:'design',title:'产品设计周会',date:'2026-09-05',duration:'32:18',lines:[{id:'d1',time:17,speaker:'alex',text:'我们先完成 iPhone 和 Mac 的连接。'},{id:'d2',time:26,speaker:'otter',text:'上滑提交后，不需要在手机上等待处理。'},{id:'d3',time:38,speaker:'alex',text:'Mac 更新转写和说话人以后，结果同步到手机。'}]},
 {id:'research',title:'客户访谈 / Northwind',date:'2026-09-04',duration:'46:05',lines:[{id:'r1',time:252,speaker:'otter',text:'我想按说话人和日期找到会议里的原话。'},{id:'r2',time:1122,speaker:'alex',text:'搜索结果应该能直接定位到录音时间。'}]},
 {id:'roadmap',title:'秋季产品路线图',date:'2026-09-02',duration:'51:22',lines:[{id:'p1',time:161,speaker:'alex',text:'先连接和传输，再做本地模型处理和跨会议问答。'},{id:'p2',time:1265,speaker:'otter',text:'离线期间保留修改，重新连接后再同步。'}]}
];
const people = {alex:'Alex',otter:'Otter'};
const $ = id => document.getElementById(id);
const esc = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clockText = s => String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0');
const key = (...parts) => parts.join(':');
const initialFields = {};
for(const [id,name] of Object.entries(people)) initialFields[key('speaker',id,'name')]=name;
for(const m of meetings){initialFields[key('meeting',m.id,'title')]=m.title;for(const l of m.lines){initialFields[key('line',l.id,'text')]=l.text;initialFields[key('line',l.id,'speaker')]=l.speaker;}}
const state={tab:'home',view:'main',origin:'home',meeting:'design',macMeeting:'design',macTab:'meetings',paired:false,connected:false,pairStep:'intro',phoneConfirmed:false,macConfirmed:false,recording:false,expanded:false,seek:0,query:'',speaker:'',from:'',to:'',editing:null,macEditing:null,searchError:'',quality:'Voice',language:'Follow System'};
let sequence=0;
const logs={phone:[],mac:[]},tasks=new Map(),drafts=new Map();
function materialize(ops){const winners=new Map();for(const op of ops){const current=winners.get(op.key);if(!current||op.order>current.order||(op.order===current.order&&op.id>current.id))winners.set(op.key,op);}const values={...initialFields};for(const [k,op]of winners)values[k]=op.value;return{values,winners};}
function mergeOperations(a,b){return [...new Map([...a,...b].map(op=>[op.id,op])).values()].sort((a,b)=>a.order-b.order||a.id.localeCompare(b.id));}
function revision(side){return logs[side].reduce((v,o)=>Math.max(v,o.order),0);}
function pending(){const a=new Set(logs.phone.map(o=>o.id)),b=new Set(logs.mac.map(o=>o.id));return [...a].filter(id=>!b.has(id)).length+[...b].filter(id=>!a.has(id)).length;}
function read(side,k){return materialize(logs[side]).values[k];}
function title(side,id){return read(side,key('meeting',id,'title'));}
function name(side,id){return read(side,key('speaker',id,'name'))||'未知说话人';}
function dot(id){return `<i class="sd ${id==='alex'?'alex':id==='otter'?'otter':'unknown'}" aria-hidden="true"></i>`;}
function meeting(id){return meetings.find(m=>m.id===id);}
function addOperation(side,k,value,source='user',batch=false){const op={id:`${side}-${++sequence}`,order:sequence,side,key:k,value,source};logs[side].push(op);if(state.connected)sync(false);if(!batch)render();return op;}
function sync(refresh=true){if(!state.connected)return;const merged=mergeOperations(logs.phone,logs.mac);logs.phone=merged.slice();logs.mac=merged.slice();for(const task of tasks.values())if(task.stage==='sending')scheduleReceipt(task);if(refresh)render();}
function isSynced(){return JSON.stringify(materialize(logs.phone).values)===JSON.stringify(materialize(logs.mac).values);}
let toastTimer;
function toast(message){$('toast').textContent=message;$('toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.add('hidden'),3000);}
function connectionText(){return !state.paired?'Connect to Mac':state.connected?'MacBook Pro · Connected':'MacBook Pro · Offline';}
function taskLabel(task,side='phone'){if(!task)return'';if(task.stage==='sending')return state.connected?'发送中，尚未收到回执':'等待连接 · 尚未送达';if(side==='phone'&&!state.connected)return 'Mac 已接收 · 离线，进度待同步';return{queued:'Mac 已接收 · 排队中',transcribing:'Mac 正在重新转写',speakers:'Mac 正在识别说话人',done:'处理完成 · '+(state.connected?'结果已同步':'等待回传')}[task.stage];}
function taskForPhone(){return tasks.get(state.meeting);}
function openMeeting(id,sec=0){state.origin=state.tab;state.meeting=id;state.macMeeting=id;state.seek=sec;state.view='detail';state.editing=null;render();}
function goBack(){state.tab=state.origin;state.view='main';state.editing=null;render();}
function gotoTab(tab){state.tab=tab;state.view='main';state.editing=null;render();}
function header(label){return `<div class="rowtop"><h2>${label}</h2>${state.tab==='home'?`<button id="connect" class="connect" onclick="openConnection()"><i class="dot ${state.connected?'on':''}"></i>${connectionText()}</button>`:''}</div>`;}
function home(){return header('Home')+`<div class="purpose">找回某个人说过的话。<br><span class="small">手机搜索随时可用；Mac 在后台处理已提交的会议。</span></div><input id="q" class="search" placeholder="搜索会议标题或内容" aria-label="搜索会议标题或内容" value="${esc(state.query)}" oninput="state.query=this.value;renderResults()"><div class="filters"><label>Speaker<select id="sp" onchange="state.speaker=this.value;renderResults()"><option value="">所有说话人</option>${Object.keys(people).map(id=>`<option value="${id}" ${state.speaker===id?'selected':''}>${esc(name('phone',id))}</option>`).join('')}</select></label><label>开始日期<input id="from" type="date" value="${state.from}" onchange="state.from=this.value;renderResults()"></label><label>结束日期（包含当天）<input id="to" type="date" value="${state.to}" onchange="state.to=this.value;renderResults()"></label></div><div id="phoneSync" class="sync-strip">${syncText('phone')}</div><div id="phoneTasks">${[...tasks.values()].map(t=>`<button class="task-mini" onclick="openMeeting('${t.meeting}')"><strong>${esc(title('phone',t.meeting))}</strong><br><span class="small">${taskLabel(t)}</span></button>`).join('')}</div><div id="results"></div>`;}
function renderResults(){if(!$('results'))return;const q=state.query.trim().toLocaleLowerCase(),active=q||state.speaker||state.from||state.to;
 if(state.from&&state.to&&state.from>state.to){$('results').innerHTML='<p role="alert" class="small">开始日期不能晚于结束日期。</p>';return;}
 if(!active){$('results').innerHTML='<h3 class="eyebrow">RECENT</h3>'+meetings.slice(0,2).map(m=>meetingRow(m)).join('');return;}
 const found=[];
 for(const m of meetings){if(state.from&&m.date<state.from||state.to&&m.date>state.to)continue;const own=m.lines.filter(l=>!state.speaker||read('phone',key('line',l.id,'speaker'))===state.speaker);if(!own.length)continue;const titleMatch=Boolean(q&&title('phone',m.id).toLocaleLowerCase().includes(q));const lines=own.filter(l=>!q||read('phone',key('line',l.id,'text')).toLocaleLowerCase().includes(q));if(!titleMatch&&!lines.length)continue;found.push(`<div class="result"><button class="result-title" onclick="openMeeting('${m.id}')"><b>${esc(title('phone',m.id))}</b><span class="small">${m.date} · ${m.duration}${titleMatch?' · 标题匹配':''}</span></button>${lines.map(l=>{const id=read('phone',key('line',l.id,'speaker'));return `<button class="snippet" onclick="openMeeting('${m.id}',${l.time})"><span class="small">${dot(id)}${esc(name('phone',id))} · ${clockText(l.time)}</span><br>${esc(read('phone',key('line',l.id,'text')))}</button>`;}).join('')}</div>`);}
 $('results').innerHTML=`<div class="eyebrow">${found.length} 场会议</div>`+(found.join('')||'<p class="small">没有匹配内容。可以调整关键词或筛选。</p>');}
function meetingRow(m){return `<button class="meeting" data-meeting="${m.id}" onclick="openMeeting('${m.id}')"><b>${esc(title('phone',m.id))}</b><span class="small">${m.date} · ${m.duration} · ${dot('alex')}${esc(name('phone','alex'))}</span></button>`;}
function library(){return header('Meetings')+[['Today','2026-09-05'],['Yesterday','2026-09-04'],['Earlier',null]].map(([label,date])=>`<h3 class="eyebrow group-label">${label}</h3>${meetings.filter(m=>date?m.date===date:m.date<'2026-09-04').map(meetingRow).join('')}`).join('');}
function settings(){return header('Settings')+`<p class="small">界面预览设置，不改变正式 App。</p><label class="meeting">语言<select onchange="state.language=this.value"><option ${state.language==='Follow System'?'selected':''}>Follow System</option><option ${state.language==='English'?'selected':''}>English</option><option ${state.language==='简体中文'?'selected':''}>简体中文</option></select></label><label class="meeting">录音质量<select onchange="state.quality=this.value"><option ${state.quality==='Voice'?'selected':''}>Voice</option><option ${state.quality==='High fidelity'?'selected':''}>High fidelity</option></select></label><button class="outline wide" onclick="resetRecordPosition()">恢复录音键位置</button>`;}
function syncText(side){return `${side==='phone'?'iPhone':'Mac'} · v${revision(side)} · ${pending()?`${pending()} 条操作待同步`:state.connected?'已同步 · 统一版本':'本地已保存'}`;}
function editor(side,k,label,multiline=false){const draftKey=side+':'+k;const value=drafts.has(draftKey)?drafts.get(draftKey):read(side,k);return `<div class="edit-form"><label>${esc(label)}${multiline?`<textarea id="${side}Edit" oninput="rememberDraft('${side}','${k}',this.value)">${esc(value)}</textarea>`:`<input id="${side}Edit" value="${esc(value)}" oninput="rememberDraft('${side}','${k}',this.value)">`}</label><div class="edit-actions"><button class="primary" id="${side}Save" onclick="saveEdit('${side}','${k}')">保存并同步</button><button onclick="cancelEdit('${side}')">取消</button></div></div>`;}
function rememberDraft(side,k,value){drafts.set(side+':'+k,value);}
function beginEdit(side,k){state[side==='phone'?'editing':'macEditing']=k;render();const input=$(side+'Edit');input?.focus();}
function cancelEdit(side){state[side==='phone'?'editing':'macEditing']=null;render();}
function saveEdit(side,k){const value=$(side+'Edit').value.trim();if(!value){toast('内容不能为空');return;}drafts.delete(side+':'+k);state[side==='phone'?'editing':'macEditing']=null;addOperation(side,k,value);toast(state.connected?'修改已同步到两端':'已保存本地操作，重连后同步');}
function renameSpeaker(side,id){beginEdit(side,key('speaker',id,'name'));}
function lineView(side,m,l){const id=read(side,key('line',l.id,'speaker')),k=key('line',l.id,'text'),edit=state[side==='phone'?'editing':'macEditing'];return `<article class="utter ${side==='phone'&&state.seek===l.time?'active':''}"><div class="utter-head"><button class="small" onclick="renameSpeaker('${side}','${id}')">${dot(id)}${esc(name(side,id))}</button><button class="small" onclick="seekLine('${side}',${l.time})">${clockText(l.time)}</button><button class="edit-link" data-edit="${side}-${l.id}" onclick="beginEdit('${side}','${k}')">编辑</button></div>${edit===k?editor(side,k,'转写文本',true):`<p>${esc(read(side,k))}</p>`}<label class="assignment">归属 <select aria-label="${side} ${l.id} speaker" onchange="addOperation('${side}','${key('line',l.id,'speaker')}',this.value)">${Object.keys(people).map(p=>`<option value="${p}" ${p===id?'selected':''}>${esc(name(side,p))}</option>`).join('')}</select></label></article>`;}
function seekLine(side,sec){if(side==='phone'){state.seek=sec;render();}else toast('原型音频定位 '+clockText(sec)+'，无真实播放');}
function speakerEditors(side){const k=state[side==='phone'?'editing':'macEditing'];return k?.startsWith('speaker:')?editor(side,k,'Speaker 名字（全局）'):'';}
function detail(){const m=meeting(state.meeting),task=tasks.get(m.id);return `<div class="nav"><button id="back" class="back" aria-label="返回" onclick="goBack()">‹</button><span class="eyebrow">MEETING</span><span class="small">iPhone</span></div><h2>${esc(title('phone',m.id))}</h2><span class="small">${m.date} · ${m.duration}</span><div class="sync-strip">${syncText('phone')}</div>${task?`<div class="task-banner">${taskLabel(task)}<br><span class="small">无需等待，可以返回 Home 或浏览其他会议。</span></div>`:''}${speakerEditors('phone')}${m.lines.map(l=>lineView('phone',m,l)).join('')}`;}
function detailBottom(){const task=taskForPhone();return `<div class="player"><div class="small">▶ ${clockText(state.seek)} / ${meeting(state.meeting).duration} · 示例播放</div><input type="range" aria-label="示例音频位置" min="0" max="1900" value="${state.seek}" oninput="state.seek=Number(this.value)"></div><div class="actions"><button class="secondary" onclick="toast('本轮不运行 iPhone 模型，原始录音保留')">Reprocessing</button><button id="process" class="primary" ${!state.connected||task?'disabled':''} onclick="openReview()">${task?'已提交 Mac':'Process by Mac'}</button></div>`;}
function openConnection(){state.view='connection';state.pairStep=state.paired?'status':'intro';render();}
function stepPair(step){state.pairStep=step;render();}
function confirmPair(side){if(side==='phone')state.phoneConfirmed=true;else state.macConfirmed=true;if(state.phoneConfirmed&&state.macConfirmed){state.paired=true;state.connected=true;state.pairStep='status';state.tab='home';state.view='main';sync(false);render();toast('已连接 MacBook Pro');}else render();}
function connectionView(){let html='<button class="back-link" onclick="gotoTab(\'home\')">‹ Home</button>';
 switch(state.pairStep){case'intro':html+='<h2>连接你的 Mac</h2><p>打开 Mac 上的 Transcript，首次连接需两端确认。</p><p class="small">本网页不扫描设备或请求系统权限。</p><button id="pairStart" class="primary wide push-bottom" onclick="stepPair(\'permission\')">查找 Mac</button>';break;
 case'permission':html+='<h2>本地网络</h2><p>正式 App 在此解释本地网络用途，再由系统请求权限。</p><div class="purpose">这是原型，不会弹出或授予真实系统权限。</div><button id="pairPermission" class="primary wide push-bottom" onclick="stepPair(\'pick\')">继续演示</button>';break;
 case'pick':html+='<h2>选择设备</h2><p class="small">示例设备，未进行真实发现。</p><button id="pairPick" class="meeting" onclick="stepPair(\'code\')"><b>MacBook Pro</b><span class="small">点击核对两端短码</span></button>';break;
 case'code':html+=`<h2>核对两端短码</h2><div class="code">482 731</div><p>在右侧 Mac 和 iPhone 分别确认相同短码。</p><p class="small">Mac：${state.macConfirmed?'已确认':'等待确认'}</p><button id="phonePairConfirm" class="primary wide push-bottom" ${state.phoneConfirmed?'disabled':''} onclick="confirmPair('phone')">${state.phoneConfirmed?'已确认，等待 Mac':'iPhone 确认'}</button>`;break;
 case'status':html+=`<h2>Connection</h2><p><i class="dot ${state.connected?'on':''}"></i>${connectionText()}</p><button class="primary wide push-bottom" onclick="toggleConnection()">${state.connected?'模拟断开':'模拟重连并返回 Home'}</button><button class="outline wide" onclick="forgetPairing()">忘记示例配对</button>`;break;}
 return html;}
function toggleConnection(){if(!state.paired){openConnection();return;}state.connected=!state.connected;if(state.connected){sync(false);if(state.view==='connection'){state.tab='home';state.view='main';}}render();toast(state.connected?'已重连：操作已合并':'已离线：可以分别编辑两端');}
function forgetPairing(){state.connected=false;state.paired=false;state.phoneConfirmed=false;state.macConfirmed=false;state.pairStep='intro';render();}
function openReview(){if(!state.connected||tasks.has(state.meeting))return;state.view='review';render();}
function submitTask(){if(state.view!=='review'||!state.connected||tasks.has(state.meeting))return;const task={id:'job-'+state.meeting,meeting:state.meeting,stage:'sending',receiptScheduled:false};tasks.set(task.meeting,task);state.view='detail';state.macTab='queue';render();scheduleReceipt(task);toast('后台发送中。你可以立即离开这场会议。');}
function scheduleReceipt(task){if(task.receiptScheduled||!state.connected||task.stage!=='sending')return;task.receiptScheduled=true;setTimeout(()=>{task.receiptScheduled=false;if(!state.connected||task.stage!=='sending')return;task.stage='queued';render();toast('Mac 已接收，后续处理无需保持 iPhone 在线');},900);}
function advanceTask(id){const task=tasks.get(id);if(!task||task.stage==='sending')return;const m=meeting(id);switch(task.stage){case'queued':task.stage='transcribing';break;case'transcribing':task.stage='speakers';addOperation('mac',key('line',m.lines[0].id,'text'),m.lines[0].text+'（Mac 重新转写示例）','model',true);break;case'speakers':addOperation('mac',key('line',m.lines[1].id,'speaker'),'alex','model',true);task.stage='done';break;}render();}
function macTask(task){return `<div class="panel"><b>${esc(title('mac',task.meeting))}</b><p>${taskLabel(task,'mac')}</p><span class="small">${task.id} · 原型手动推进模型阶段</span><div class="edit-actions">${task.stage!=='done'&&task.stage!=='sending'?`<button class="primary" data-advance="${task.meeting}" onclick="advanceTask('${task.meeting}')">${{queued:'开始处理',transcribing:'完成转写',speakers:'完成说话人识别'}[task.stage]}</button>`:''}<button onclick="state.macMeeting='${task.meeting}';state.macTab='meetings';render()">查看 / 编辑会议</button></div></div>`;}
function renderMac(){document.querySelectorAll('[data-mactab]').forEach(b=>b.classList.toggle('selected',b.dataset.mactab===state.macTab));$('macDevice').innerHTML=`<i class="dot ${state.connected?'on':''}"></i>${connectionText()}<br><span>${syncText('mac')}</span>`;
 if(state.view==='connection'&&state.pairStep==='code'){$('macTitle').textContent='Pair iPhone';$('macContent').innerHTML=`<div class="panel"><div class="code">482 731</div><p>确认手机显示相同短码。示例配对，不建立真实连接。</p><button id="macPairConfirm" class="primary wide" ${state.macConfirmed?'disabled':''} onclick="confirmPair('mac')">${state.macConfirmed?'Mac 已确认':'Mac 确认'}</button></div>`;return;}
 $('macTitle').textContent=state.macTab==='queue'?'Processing':'Meetings';
 if(state.macTab==='queue'){$('macContent').innerHTML=[...tasks.values()].map(macTask).join('')||'<div class="panel">还没有任务。从 iPhone 会议详情上滑提交。</div>';return;}
 const m=meeting(state.macMeeting);$('macContent').innerHTML=`<label class="small">示例会议<select id="macMeetingSelect" onchange="state.macMeeting=this.value;state.macEditing=null;render()">${meetings.map(m=>`<option value="${m.id}" ${m.id===state.macMeeting?'selected':''}>${esc(title('mac',m.id))}</option>`).join('')}</select></label><h3>${esc(title('mac',m.id))}</h3><div class="sync-strip">${syncText('mac')}</div>${tasks.has(m.id)?macTask(tasks.get(m.id)):''}${speakerEditors('mac')}${m.lines.map(l=>lineView('mac',m,l)).join('')}`;}
function renderLog(){const union=mergeOperations(logs.phone,logs.mac),winner=materialize(union).winners;$('operationLog').innerHTML=union.length?union.slice().reverse().map(op=>`<div class="op"><span class="op-index">#${op.order}</span><span><b>${op.side==='phone'?'iPhone':'Mac'} ${op.source==='model'?'模型结果':'用户修改'}</b> · ${esc(op.key)}<br><span>${esc(op.value)}</span></span><span class="op-state">${winner.get(op.key).id===op.id?'最新':'已被后续操作替代'}</span></div>`).join(''):'<p class="small">还没有修改。编辑任一端的转写、名字或片段归属，就会记录一条操作。</p>';$('convergence').textContent=state.connected&&isSynced()?`两端已收敛 · v${revision('phone')}`:`${pending()} 条待同步 · ${isSynced()?'当前内容一致':'两端有离线差异'}`;}
function render(){const focus=document.activeElement,focusID=focus?.id,selection=focus&&['INPUT','TEXTAREA'].includes(focus.tagName)?[focus.selectionStart,focus.selectionEnd]:null;
 $('detailBottom')?.remove();$('screen').classList.toggle('hidden',!['main','detail'].includes(state.view));$('tabs').classList.toggle('hidden',state.view!=='main');$('modal').classList.toggle('hidden',state.view!=='connection');$('review').classList.toggle('hidden',state.view!=='review');$('receipt').classList.add('hidden');$('rec').classList.toggle('hidden',state.view!=='main'||state.recording);$('recording').classList.toggle('hidden',!state.recording||!state.expanded);$('mini').classList.toggle('hidden',!state.recording||state.expanded||['review','connection'].includes(state.view));document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));
 $('demoConnect').textContent=state.connected?'模拟断开连接':state.paired?'模拟重连并合并操作':'开始配对演示';$('demoFinish').textContent='查看 Mac 处理队列';
 if(state.view==='main'){$('content').innerHTML=state.tab==='home'?home():state.tab==='meetings'?library():settings();if(state.tab==='home')renderResults();}
 if(state.view==='detail'){$('content').innerHTML=detail();const bottom=document.createElement('div');bottom.id='detailBottom';bottom.className='bottom';bottom.innerHTML=detailBottom();$('screen').append(bottom);}
 if(state.view==='connection')$('modal').innerHTML=connectionView();
 if(state.view==='review'){$('reviewTitle').textContent=title('phone',state.meeting);$('reviewConnection').textContent=state.connected?'Connected':'Offline';$('swipe').textContent=state.connected?'Swipe up to Submit':'Mac Offline · 返回或重连';$('swipe').setAttribute('aria-disabled',String(!state.connected));$('card').style.transform='';}
 renderMac();renderLog();pos();
 if(focusID&&$(focusID)){const input=$(focusID);input.focus({preventScroll:true});if(selection&&selection[0]!==null)try{input.setSelectionRange(...selection);}catch{}}
}
let recordPosition={x:.84,y:.85};try{const saved=JSON.parse(localStorage.getItem('v5rec'));if(saved&&Number.isFinite(saved.x)&&Number.isFinite(saved.y))recordPosition=saved;}catch{}
function bounds(){return{left:8,right:Math.max(8,$('phone').clientWidth-62),top:78,bottom:Math.max(78,$('phone').clientHeight-136)};}
function pos(){const b=bounds();$('rec').style.left=(b.left+Math.max(0,Math.min(1,recordPosition.x))*(b.right-b.left))+'px';$('rec').style.top=(b.top+Math.max(0,Math.min(1,recordPosition.y))*(b.bottom-b.top))+'px';}
function resetRecordPosition(){recordPosition={x:.84,y:.85};try{localStorage.removeItem('v5rec');}catch{}pos();}
function startRecording(){if(state.recording)return;state.recording=true;state.expanded=true;render();}
let recordDrag=null,suppressTap=false;
$('rec').onpointerdown=e=>{if(e.button>0)return;recordDrag={x:e.clientX,y:e.clientY,left:parseFloat($('rec').style.left),top:parseFloat($('rec').style.top),moved:false};suppressTap=false;$('rec').setPointerCapture(e.pointerId);};
$('rec').onpointermove=e=>{if(!recordDrag)return;const dx=e.clientX-recordDrag.x,dy=e.clientY-recordDrag.y;recordDrag.moved ||= Math.hypot(dx,dy)>8;if(!recordDrag.moved)return;const b=bounds(),left=Math.max(b.left,Math.min(b.right,recordDrag.left+dx)),top=Math.max(b.top,Math.min(b.bottom,recordDrag.top+dy));recordPosition={x:(left-b.left)/(b.right-b.left),y:(top-b.top)/(b.bottom-b.top)};pos();};
$('rec').onpointerup=()=>{if(!recordDrag)return;suppressTap=recordDrag.moved;recordDrag=null;if(suppressTap)try{localStorage.setItem('v5rec',JSON.stringify(recordPosition));}catch{}};
$('rec').onpointercancel=()=>{recordDrag=null;suppressTap=true;};$('rec').onclick=()=>{if(suppressTap){suppressTap=false;return;}startRecording();};$('rec').onkeydown=e=>{if(e.key.toLowerCase()==='r'){e.preventDefault();resetRecordPosition();}};
let swipeStart=null;
for(const id of ['grip','swipe']){const node=$(id);node.onpointerdown=e=>{if(e.button>0||!state.connected)return;swipeStart={y:e.clientY,distance:0};$('card').classList.remove('settle');node.setPointerCapture(e.pointerId);};node.onpointermove=e=>{if(!swipeStart)return;swipeStart.distance=Math.max(0,Math.min(320,swipeStart.y-e.clientY));$('card').style.transform=`translateY(-${swipeStart.distance}px)`;$('swipe').textContent=swipeStart.distance>=92?'Release to Submit':'Swipe up to Submit';};node.onpointerup=()=>{if(!swipeStart)return;const distance=swipeStart.distance;swipeStart=null;if(distance>=92)submitTask();else{$('card').classList.add('settle');$('card').style.transform='translateY(0)';$('swipe').textContent='Swipe up to Submit';}};node.onpointercancel=()=>{swipeStart=null;$('card').style.transform='';};node.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();submitTask();}};}
let edge=null;$('phone').addEventListener('pointerdown',e=>{const b=$('phone').getBoundingClientRect();if(state.view==='detail'&&e.clientX-b.left<28)edge={x:e.clientX,y:e.clientY};});window.addEventListener('pointerup',e=>{if(edge&&e.clientX-edge.x>65&&Math.abs(e.clientY-edge.y)<60)goBack();edge=null;});window.addEventListener('pointercancel',()=>edge=null);
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>gotoTab(b.dataset.tab));$('demoConnect').onclick=toggleConnection;$('demoFinish').onclick=()=>{state.macTab='queue';render();};$('edit').onclick=()=>{state.view='detail';render();};$('collapse').onclick=()=>{state.expanded=false;render();};$('expand').onclick=()=>{state.expanded=true;render();};$('stop').onclick=$('ministop').onclick=()=>{state.recording=false;state.expanded=false;render();toast('演示录音已停止，没有采集音频');};window.addEventListener('resize',pos);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&state.view==='review'){state.view='detail';render();}});
// Read-only observability for local runnable checks.
window.demoSnapshot=()=>({state:{...state},phone:materialize(logs.phone).values,mac:materialize(logs.mac).values,logs:JSON.parse(JSON.stringify(logs)),tasks:[...tasks.values()].map(t=>({...t})),pending:pending()});
render();
